config:
  DATA:
    DATA_SOURCE: data/raw
    DATA_SAVE: data/tiles
    DATASET_NAMES: Test
    EXTENSION_SAVE: tiff
  PARAMETERS:
    MAGNIFICATION: [5, 10, 20, 40]
    NB_TILES: 5
    OVERLAP:
      NB_PIXEL: 0
    BACKGROUND:
      THRESHOLD: 5e-4
  VERBOSE: True
  SEED_VALUE: 42
  MULTI_PROCESSING: True