DATA:
  DATA_SOURCE: ../data/raw/
  DATA_SAVE: ../data/tiles/
  DATA_SAVE_PLOT: ../data/plot/
  DATASET_NAMES: Test
  EXTENSION_SAVE: tiff
  SAVE_PLOT_IMG: True
PARAMETERS:
  DOWNSAMPLE_FACTOR: 64
  MAGNIFICATIONS: [5, 10, 20, 40]
  NB_TILES: 5
  OVERLAP:
    NB_PIXEL: 0
  BACKGROUND:
    THRESHOLD: 5e-4
  OTSU:
    THRESHOLD: 0.05
VERBOSE: True
SEED_VALUE: 42
MULTI_PROCESSING: True