DATA:
  DATA_SOURCE: ../data/raw/
  DATA_SAVE_TISSUE_MASKS: ../data/masks/
  DATA_SAVE_TILES: ../data/tiles/
  DATA_SAVE_PLOT: ../data/plot/
  DATASET_NAMES: Test
  EXTENSION_SAVE: tiff
  SAVE_PLOT_IMG: False
PARAMETERS:
  DOWNSAMPLE_FACTOR: 128
  MAGNIFICATIONS: [5, 10, 20, 40]
  NB_TILES: 5
  TILE_SIZE: 224
  OVERLAP:
    NB_PIXEL: 0
  BACKGROUND:
    THRESHOLD: 0.0005
  OTSU:
    THRESHOLD: 0.05
  SMALL_OBJ:
    TOLERANCE: 20
VERBOSE: True
SEED_VALUE: 42
MULTI_PROCESSING: True